### ISSUE TITLE
Name conflict

### ISSUE THREAD

**Issue by linkdd** [PartehDev/NumLang#1]
Hello there!

I enjoyed your project, it's a fun one. I discovered it via the [Esolang](https://esolangs.org/wiki/Letlang) website.

But unfortunately, its name clashes with my own project [Letlang](https://letlang.dev).

I started working on it back in 2021 and created the repository in the beginning of 2022 (see [commit](https://github.com/linkdd/letlang/commit/806fad358eb00d40e0603db45e8c04375b55b721)).

While I don't have a trademark for the name and can't enforce anything, and while the license is MIT which does not protect the name, would you mind changing the name of your language to avoid confusion? (if not, then it's ok, I won't mind, though a note in your readme and the wiki page would be appreciated).

Thank you for your time and have a great day/evening/whatever depending on when you read this message 🙂

Best regards.

**Comment by PartehDev** [comment]
Hey! Thanks for reaching out! I'm not too concerned with the name of my project, since I didn't know any other projects called "Letlang", but I'm okay with changing the name of the language to not conflict with other project. Once again, thank you for reaching out, and have a great day!
